repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: debug-statements
    - id: name-tests-test
      args: ['--django']  # PyCharm requires tests to have 'test' as prefix, not a suffix
    - id: check-json
    - id: check-yaml

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      args: [--max-line-length=120]
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      additional_dependencies:
        - 'types-requests'
        - 'types-PyYAML'

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.23.0'
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@5.32.0"
          - "@typescript-eslint/parser@5.32.0"
          - "eslint@7.14.0"
          - "eslint-config-prettier@6.15.0"
          - "eslint-plugin-prettier@3.1.4"
