name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtualenv
        run: |
          python -V
          python -m pip install virtualenv pipdeptree
          virtualenv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Test pre-commit hooks
        run: |
          python -m pip install .
          python -m pip freeze
          pipdeptree
          pre-commit run --all-files

      - name: Test with tox
        run: |
          tox -e py

      - name: Wheel
        run: |
          python setup.py sdist
