name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Setup virtualenv
        run: |
          python -V
          python -m pip install virtualenv pipdeptree
          virtualenv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Test pre-commit hooks
        run: |
          pip install .[tests]
          pip freeze
          pipdeptree
          pre-commit run --all-files

      - name: Test with tox
        run: |
          tox -e py38

      - name: Wheel
        run: |
          python setup.py sdist
